### ISSUE TITLE
How to obfuscate multi-files with same name?

### ISSUE THREAD

**Issue by lennylxx** [obfuscar/obfuscar#163]
I have a .NET Core project called FooBar.csproj, and it's targeting multiple frameworks.
`<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`

The build output will be multiple files with same name like this:
```
outputFolder/net461/FooBar.dll
outputFolder/netstandard2.0/FooBar.dll
```

How do you write the config file `obfuscar.xml` to obfuscate these files in one-run?
Settings like below won't work since these two files will conflict.
```
  <Var name="InPath" value=".\Obfuscator_Input" />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="KeyFile" value=".\keypair.snk" />

  <Module file="$(InPath)\net461\FooBar.dll" />
  <Module file="$(InPath)\netstandard2.0\FooBar.dll" />
```

Error message:
```
Unhandled Exception: System.IO.IOException: The process cannot access the file 'Obfuscator_Output\FooBar.dll' because it is being used by another process.
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
     at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException)
     at Obfuscar.Obfuscator.RunRules()
     at Obfuscar.Program.Main(String[] args)
```

**Comment by lextm** [comment]
Use two config files, and then run `Obfuscar file1 file2`.
