### ISSUE TITLE
Could not find a method 'ConfigureProduction' or 'Configure', when trying to run an obfuscated dotnet core dll

### ISSUE THREAD

**Issue by vishnuraom** [obfuscar/obfuscar#165]
Detailed Exception:
Application startup exception: System.InvalidOperationException: A public method named 'ConfigureProduction' or 'Configure' could not be found in the ' .`' type.
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.FindMethod(Type startupType, String methodName, String environmentName, Type returnType, Boolean required)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.FindConfigureDelegate(Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

I'm sure I have that method in my code.
Is this issue anyway related to the reflection being used by dotnet core to determine the correct configure method as mentioned here [url](https://sankarsan.wordpress.com/2018/02/25/asp-net-core-application-startup-part2/) ?
Lastly, how can I resolve this issue?
TIA

**Comment by vishnuraom** [comment]
Thanks, it work's now.

**Comment by aurangzeb-khan** [comment]
Hello @vishnuraom 
Can you please let me know how did you solve this issue?

**Comment by BShindler** [comment]
@lextm Can you help me please? I have the same problem and I tried to exclude the `Configure` function by:
`<SkipMember signature="System.Void MyNamespace.Startup::Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder, Microsoft.AspNetCore.Hosting.IWebHostEnvironment)" />`
but the same exception still occurs.
I see in the decompiled code that the function name is still hidden.
What can be wrong?
