### ISSUE TITLE
WpfToolkitTests.CheckGeneric test fails

### ISSUE THREAD

**Issue by garymcleanhall** [obfuscar/obfuscar#181]
The app I'm building fails to obfuscate with Obfuscar.

I cloned this repo and ran tests and the `WpfToolkitTests.CheckGeneric` test fails with a null reference exception:

```
System.NullReferenceException
Object reference not set to an instance of an object.
   at Ricciolo.StylesExplorer.MarkupReflection.XmlBamlReader.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at Obfuscar.Obfuscator.GetXamlDocuments(AssemblyDefinition library)
   at Obfuscar.Obfuscator.RenameTypes()
   at ObfuscarTests.TestHelper.Obfuscate(String xml, Boolean hideStrings) in C:\Users\GaryMcLeanHall\Dev\obfuscar\Tests\TestHelper.cs:line 113
   at ObfuscarTests.WpfToolkitTests.CheckGeneric() in C:\Users\GaryMcLeanHall\Dev\obfuscar\Tests\WpfToolkitTests.cs:line 79
```

I fixed this test (and enabled my app to be obfuscated) by making some code inside `XmlBamlReader` more defensive:

```
public override string Value
{
    get {
        XmlBamlNode node = CurrentNode;
        if (node is XmlBamlSimpleProperty bamlSimpleProperty)
            return bamlSimpleProperty.Value;
        else if (node is XmlBamlProperty bamlProperty && bamlProperty.Value != null)
            return bamlProperty.Value.ToString();
        else if (node is XmlBamlText bamlText)
            return bamlText.Text;
        else if (node is XmlBamlElement)
            return String.Empty;

        return String.Empty;
    }
}
```

However, this is ILSpy code, so I guess I would need to raise a PR there? However, ILSpy works and no relevant tests fail so I can imagine I'll have a problem trying to push this through there.

---

PR raised on ILSpy here: https://github.com/icsharpcode/ILSpy/pull/1410

**Comment by lextm** [comment]
The latest code base removed dependencies on ILSpy. I will commit over the weekend.

**Comment by garymcleanhall** [comment]
Just to let you know, the replacement Baml processor works for me for `HidePrivateApi = false`, but not when it is set to `true`.

I'll investigate further and may open a new issue if necessary.

Thanks for getting to this so quickly.
