### ISSUE TITLE
System.NotSupportedException in  DLL (.Net framework 4.0)

### ISSUE THREAD

**Issue by germanyesid** [obfuscar/obfuscar#208]
When I try to obfuscate a dll .Net FrameWork 4.0, I get the following message

```
Processing assembly: Genericos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  Loading assemblies...Extra framework folders: Done.
  Hiding strings...    
  Unhandled Exception: System.NotSupportedException: Cannot read resources that depend on serialization.
     at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
     at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
     at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
     at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
     at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
     at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
     at Obfuscar.Obfuscator.GetXamlDocuments(AssemblyDefinition library) in F:\obfuscar\Obfuscar\Obfuscator.cs:line 702
     at Obfuscar.Obfuscator.RenameTypes() in F:\obfuscar\Obfuscar\Obfuscator.cs:line 502
     at Obfuscar.Obfuscator.RunRules() in F:\obfuscar\Obfuscar\Obfuscator.cs:line 129
     at Obfuscar.Program.Main(String[] args) in F:\obfuscar\GlobalTools\Program.cs:line 115
  Renaming:  fields...Parameters...Properties...Events...Methods...Types...Obfuscation complete.
```
I tried disabling "HideStrings" `<Var name="HideStrings" value="false" /> `but I get the same result

**Comment by lextm** [comment]
Are you using the .NET Core global tool to work on .NET Framework assemblies? That's not supported yet, and .NET Core 3.0 RTM should address that.

**Comment by lextm** [comment]
Similar to #268 but the error message is different on .NET Framework. #324 gave a setting to disable the resource file analysis, so it should fix this as well.
