### ISSUE TITLE
Crash on a large project

### ISSUE THREAD

**Issue by gunsh** [obfuscar/obfuscar#231]
I have a very large project that I would like to obfuscate. After including all of the assemblies I get the error below. I have managed to pinpoint one particular assembly, exclude it and get the tool to run without crashing (but that's obviously not acceptable).

I have downloaded source code, upgraded Mono.Cecil from 0.10.4 to 0.11.0 without any change to the outcome or the crash output.

I am wondering how to even begin debugging this one. I don't know what an "A.b" is as the "Mapping.xml" has not been written out yet.

> Loading assemblies...Extra framework folders: Done.
Hiding strings...
Renaming:  fields...Parameters...Properties...Events...Methods...Types...Done.
Saving assemblies...
Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve A.b
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeEnumValue(TypeReference enum_type, Object value)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeElement(TypeReference type, CustomAttributeArgument argument)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeConstructorArguments(CustomAttribute attribute)
   at Mono.Cecil.MetadataBuilder.GetCustomAttributeSignature(CustomAttribute attribute)
   at Mono.Cecil.MetadataBuilder.AddCustomAttributes(ICustomAttributeProvider owner)
   at Mono.Cecil.MetadataBuilder.AddProperty(PropertyDefinition property)
   at Mono.Cecil.MetadataBuilder.AddProperties(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException)
   at Obfuscar.Obfuscator.RunRules()
   at Obfuscar.Program.Main(String[] args)

**Comment by gunsh** [comment]
I have managed to reproduce this issue. Please have a look at https://github.com/gunsh/obfuscar-attribute-crash

This is related to having TWO assemblies. One assembly defines an attribute (`ModeAttribute`) and an enum (`Mode`) while the other one has a class (`Program`) with a property (`Property`) decorated by  `ModeAttribute` that also uses `Mode` enum.

The thing is that if `Mode` is obfuscated, Obfuscar crashes. On the other hand if the `Mode` is marked with `[Obfuscation]`, the crash goes away. If `ModeAttribute` is stripped from `Property` the crash also goes away. If `ConsoleApp14.exe` is stripped from `Obfuscar.xml` the crash also goes away.

Last but not least, unlike `Program` class in `ConsoleApp14` assembly, having a similar class `Class1` in  assembly `ClassLibrary1` where `Mode` is also declared having the same decorated property **does not** cause obfuscation issues or a crash.

So there is something about using an obfuscated type in an attribute decoration of an assembly that is different to the assembly of the obfuscated type.

At the very least Obfuscar should not crash. Best possible scenario is of course to fix and support this but next best thing would be to output a warning about an obfuscated type being used in a different assembly in attribute declaration. So if impossible to support, shoot an error about it.

**Comment by Edward-Alchikha** [comment]
I've also bumped into this problem and it still exists in 2.2.37. Using `[Obfuscation(Exclude = true)]` on the enum type works for me.

For a more permanent fix to make sure I don't bump into it again I am using `<SkipEnums value="true" />` within all the `<Module>`s and that works fine as a workaround until this issue is fixed.
