### ISSUE TITLE
Crash obfuscating two assemblies where one references the other's obfuscated enum in a method with a default parameter value

### ISSUE THREAD

**Issue by gunsh** [obfuscar/obfuscar#235]
Similar to #231 there is a crash when the main assembly references the other assembly's enum as a method parameter with a default value. Version 2.2.24 is affected. Have a look at: https://github.com/gunsh/obfuscar-default-parameter-enum-value

Please note that once the default value is removed from `Program.Method` -OR- if `[Obfuscation]` attribute is applied to `Mode` enum, the issue goes away.

> Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve A.A
2>     at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
2>     at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
2>     at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
2>     at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
2>     at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
2>     at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
2>     at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
2>     at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
2>     at Mono.Cecil.MetadataBuilder.AddTypes()
2>     at Mono.Cecil.MetadataBuilder.BuildTypes()
2>     at Mono.Cecil.MetadataBuilder.BuildModule()
2>     at Mono.Cecil.MetadataBuilder.BuildMetadata()
2>     at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
2>     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
2>     at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
2>     at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
2>     at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException)
2>     at Obfuscar.Obfuscator.RunRules()
2>     at Obfuscar.Program.Main(String[] args)

**Comment by Jascen** [comment]
Thanks for opening this.

I ran into a similar issue and this helped me locate what was different this time around. In my instance, I also have an Enum in a library (netstandard2.0) being obfuscated and I am referencing it from an exe (netcoreapp3.1). Adding the Obfuscation attribute does resolve my issue.

```
Mono.Cecil.ResolutionException: Failed to resolve B.BA
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException)
```

**Comment by Whathecode** [comment]
This problem seems to have been around for a while. I doubt it is still "in progress". :)

Any update?

**Comment by lextm** [comment]
It seems to be resolved in v3.0 after migrating to System.Reflection.Metadata.
