### ISSUE TITLE
The method X is not a property accessor 

### ISSUE THREAD

**Issue by ebicoglu** [obfuscar/obfuscar#247]
We get an exception when we obfuscate the lambda expression. It throws the exception below

> System.ArgumentException: 'The method 'A.A`3[System.Nullable`1[System.Guid],System.String,System.String].A' is not a property accessor (Parameter 'members[0]')'

*Stack trace:*
```
  at System.Linq.Expressions.Expression.GetProperty(MethodInfo mi, String paramName, Int32 index)
  at System.Linq.Expressions.Expression.ValidateAnonymousTypeMember(MemberInfo& member, Type& memberType, String paramName, Int32 index)
  at System.Linq.Expressions.Expression.ValidateNewArgs(ConstructorInfo constructor, ReadOnlyCollection`1& arguments, ReadOnlyCollection`1& members)
  at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments, IEnumerable`1 members)
  at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments, MemberInfo[] members)
  at LanguageManagement.EntityFramework.LanguageManagementDbContextModelCreatingExtensions.찂.찂(EntityTypeBuilder`1 )
  at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
  at LanguageManagement.EntityFramework.LanguageManagementDbContextModelCreatingExtensions.ConfigureLanguageManagement(ModelBuilder builder, Action`1 optionsAction)
  at HotelBooker.EntityFrameworkCore.HotelBookerMigrationsDbContext.OnModelCreating(ModelBuilder builder) in C:\Temp\obfuscation\src\HotelBooker.EntityFrameworkCore.DbMigrations\EntityFrameworkCore\HotelBookerMigrationsDbContext.cs:line 42
  at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
  at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
  at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
  at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
```

```
namespace LanguageManagement.EntityFramework
{
    public static class MyExtensions
    {
        public static void ConfigureLanguageManagement(
            this ModelBuilder builder,
            Action<ConfigurationOptions> optionsAction = null)
        {
            Check.NotNull(builder, nameof(builder));

            var options = new ConfigurationOptions(
                "App",
                "Test"
            );

            optionsAction?.Invoke(options);

//////// this line throws error. lambda expression  //////////////
            builder.Entity<Language>(b =>
            {
                b.ToTable(options.TablePrefix + "Languages", options.Schema);

                b.ConfigureFullAuditedAggregateRoot();

                b.ConfigureFullAudited();
                b.Property(x => x.CultureName).IsRequired().HasColumnName(nameof(Language.CultureName)).HasMaxLength(LanguageConsts.MaxCultureNameLength);
                b.Property(x => x.UiCultureName).IsRequired().HasColumnName(nameof(Language.UiCultureName)).HasMaxLength(LanguageConsts.MaxUiCultureNameLength);
                b.Property(x => x.DisplayName).IsRequired().HasColumnName(nameof(Language.DisplayName)).HasMaxLength(LanguageConsts.MaxDisplayNameLength);
                b.Property(x => x.FlagIcon).IsRequired(false).HasColumnName(nameof(Language.FlagIcon)).HasMaxLength(LanguageConsts.MaxFlagIconLength);
                b.Property(x => x.IsEnabled).IsRequired().HasColumnName(nameof(Language.IsEnabled));
            });

            builder.Entity<LanguageText>(b =>
            {
                b.ToTable(options.TablePrefix + "LanguageTexts", options.Schema);

                b.ConfigureMultiTenant();
                b.ConfigureAudited();
                b.Property(x => x.ResourceName).IsRequired().HasColumnName(nameof(LanguageText.ResourceName)).HasMaxLength(LanguageTextConsts.MaxResourceNameLength);
                b.Property(x => x.Name).IsRequired().HasColumnName(nameof(LanguageText.Name)).HasMaxLength(LanguageTextConsts.MaxKeyNameLength);
                b.Property(x => x.Value).IsRequired().HasColumnName(nameof(LanguageText.Value)).HasMaxLength(LanguageTextConsts.MaxValueLength);
                b.Property(x => x.CultureName).IsRequired().HasColumnName(nameof(LanguageText.CultureName)).HasMaxLength(LanguageTextConsts.MaxCultureNameLength);

                b.HasIndex(x => new {x.TenantId, x.ResourceName, x.CultureName});
            });
        }
    }
}
```

when we set the `HidePrivateApi` to `false` it works.

**Comment by lextm** [comment]
As the top of the call stack indicates usage of reflection (`MethodInfo`), there must be certain things to be excluded from obfuscation.

You have to dig further on your own to locate that detail and then revise your Obfuscar configuration with exclude rules.
