### ISSUE TITLE
Mono.Cecil.ResolutionException: Failed to resolve System.IO.FileShare

### ISSUE THREAD

**Issue by monty241** [obfuscar/obfuscar#248]
[For reference purposes when people run across the same issue]

Also seen on System.Runtime.Reflection.

Running Obfuscar 2.2.19 you might get output such as:

```
Obfuscar.Console.exe "c:\temp\folder-deployment\acme SQL\17.33.201\xml\Acme.SQL.17.33.201-BETA-netcoreapp2.1.xml"
Note that Rollbar API is enabled by default to collect crashes. If you want to opt out, please run with -s switch
Loading project c:\temp\folder-deployment\Acme SQL\17.33.201\xml\Acme.SQL.17.33.201-BETA-netcoreapp2.1.xml...Processing assembly: Acme.Data.Interfaces, Version=17.33.201.0, Culture=neutral, PublicKeyToken=9a7f15e5fb1161b2
Loading assemblies...Extra framework folders: Done.
Hiding strings...
Renaming:  fields...Parameters...Properties...Events...Methods...Types...Done.
Saving assemblies...Do KV Acme.Data.Interfaces.dll
Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve System.IO.FileShare
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException)
   at Obfuscar.Obfuscator.RunRules()
   at Obfuscar.Program.Main(String[] args)
```

**Comment by monty241** [comment]
Problem fixed by upgrading from 2.2.19 to 2.2.25.
