### ISSUE TITLE
Assembly signing for .net core 3.x

### ISSUE THREAD

**Issue by endink** [obfuscar/obfuscar#258]
when i use global tool for .net core 3.1 app:
get message:
```
Hiding strings...
Renaming:  fields...Parameters...Properties...Events...Methods...Types...Done.
Saving assemblies...
Unhandled Exception: System.PlatformNotSupportedException: Strong-name signing is not supported on this platform.
   at System.Reflection.StrongNameKeyPair.get_PublicKey()
   at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException) in F:\obfuscar\Obfuscar\Obfuscator.cs:line 242
   at Obfuscar.Obfuscator.RunRules() in F:\obfuscar\Obfuscar\Obfuscator.cs:line 137
   at Obfuscar.Program.Main(String[] args) in F:\obfuscar\GlobalTools\Program.cs:line 115

```

BTW, Whether .net core 3.1 is supported in PostBuildEvent mode  (use nuget packages)？

Hope to be able to clearly indicate the currently supported .net platform in the documentation.

**Comment by lextm** [comment]
You should avoid strong naming .NET Core assemblies. That exception is expected.

PostBuildEvent is fully supported even in SDK based projects.

Unless explicitly stated, you should assume this tool works for all cases (as Mono Cecil does).

**Comment by endink** [comment]
Alright, thanks !
