### ISSUE TITLE
Using EmguCV and "default" keyword as method parameter breaks obfuscar.

### ISSUE THREAD

**Issue by 13cbt13** [obfuscar/obfuscar#262]
So I started to get "Obfuscar.console.exe exited with code -532462766" with 

`Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Emgu.CV.World'`

This is how I started getting it;

```
private void SomeFunction(TemplateMatchingType tmt = default)
{
    //adding -> "TemplateMatchingType tmt = default" breaks obfuscar
}
```
Removing the **default** parameter resolves the issue.

Luckily, this was the only change I made before starting to get the error or I could have never pinpointed this.

I'm fine with not using default parameter here, but just wanted to put this out there in case someone needed this information.

Posting the full exception below;

```
 Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Emgu.CV.World, Version=4.1.1.3497, Culture=neutral, PublicKeyToken=7281126722ab4438'
     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Obfuscar.AssemblyCache.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
     at Mono.Cecil.TypeReference.Resolve()
     at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
     at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
     at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
     at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
     at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
     at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
     at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddTypes()
     at Mono.Cecil.MetadataBuilder.BuildTypes()
     at Mono.Cecil.MetadataBuilder.BuildModule()
     at Mono.Cecil.MetadataBuilder.BuildMetadata()
     at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func 3 read)
     at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable 1 stream, WriterParameters parameters)
     at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable 1 stream, WriterParameters parameters)
     at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException)
     at Obfuscar.Obfuscator.RunRules()
     at Obfuscar.Program.Main(String[] args)

```

**Comment by lextm** [comment]
Not sure why Mono Cecil wants to resolve that assembly, but you should be able to avoid the issue by making that assembly available in search path, https://docs.obfuscar.com/getting-started/configuration.html#assembly-search-path-2-2-5
