### ISSUE TITLE
WPF .Net Core 3.1.3 Application + Class Library "System.Windows.Markup.StaticExtension"

### ISSUE THREAD

**Issue by dawoat** [obfuscar/obfuscar#272]
The dll was Obfuscated. But trying to start the Application throws the Error:

EXCEPTION: System.Windows.Markup.XamlParseException: Die Angabe eines Werts für "System.Windows.Markup.StaticExtension" führte zu einer Ausnahme.
 ---> System.ArgumentException: Der StaticExtension-Wert "BTM.GUI.Commands.AppCommands.ctrlBaustelleOpen" kann nicht zu einer Enumeration, einem statischen Feld oder einer statischen Eigenschaft aufgelöst werden.
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="D:\SourceCode\BTM\Output\Release\netcoreapp3.1\" />
  <Var name="OutPath" value="D:\SourceCode\BTM\Output\Release\netcoreapp3.1\Obfuscator_Output" />
  
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="false" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />

  <Module file="$(InPath)\BTM.GUI.dll" />
</Obfuscator>

**Comment by dawoat** [comment]
used obfuscator.xml:

<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="D:\SourceCode\BTM\Output\Release\netcoreapp3.1\" />
  <Var name="OutPath" value="D:\SourceCode\BTM\Output\Release\netcoreapp3.1\Obfuscator_Output" />
  
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="false" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />

  <Module file="$(InPath)\BTM.GUI.dll" />
</Obfuscator>

**Comment by lextm** [comment]
No plan to further improve WPF related features (too much work).

Pull requests are welcome.

**Comment by lextm** [comment]
Duplicate to #551
