### ISSUE TITLE
Cannot read resources that depend on serialization

### ISSUE THREAD

**Issue by textproofreading** [obfuscar/obfuscar#282]
I use obfuscar in my small and simple c# application with default config file.

My project has **no any resources content** , file / icon ... 

The error message show as below: 

```

Loading project obfuscar_settings.config...
Processing assembly: XXX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Loading assemblies...Extra framework folders: Done.

Hiding strings...

Renaming:  fields...Parameters...Properties...Events...Methods...Types...

Unhandled Exception: System.NotSupportedException: Cannot read resources that depend on serialization.
   at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at Obfuscar.Obfuscator.GetXamlDocuments(AssemblyDefinition library) in E:\obfuscar\Obfuscar\Obfuscator.cs:line 723
   at Obfuscar.Obfuscator.RenameTypes() in E:\obfuscar\Obfuscar\Obfuscator.cs:line 523


````

before I send this post , I searched for a while , but still has no any clue for solve above problem .

thanks for you help.

**Comment by lextm** [comment]
Duplicate to #208
