### ISSUE TITLE
Issue when obfuscating a library which is referenced by a web api project

### ISSUE THREAD

**Issue by zlatkolakisic** [obfuscar/obfuscar#296]
### System in use
- .net core 3.1
- Release config
- Project type: Class Library

### Description
When obfuscating a project that is directly referenced by the main .net core project and running the main webapi project, we get this error
`System.AggregateException: An error occurred while writing to logger(s). (Value does not fall within the expected range. (Parameter 'typeName@57'))
 ---> System.ArgumentException: Value does not fall within the expected range. (Parameter 'typeName@57')
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
   at System.Diagnostics.StackTrace.TryResolveStateMachineMethod(MethodBase& method, Type& declaringType)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Exception.get_StackTrace()
   at System.Exception.ToString()
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.CreateDefaultLogMessage(StringBuilder logBuilder, LogLevel logLevel, String logName, Int32 eventId, String message, Exception exception)
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.WriteMessage(LogLevel logLevel, String logName, Int32 eventId, String message, Exception exception)
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
   at Microsoft.AspNetCore.Diagnostics.DiagnosticsLoggerExtensions.UnhandledException(ILogger logger, Exception exception)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: Keep-Alive
Content-Type: application/json; charset=UTF-8
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en,en-US;q=0.9,hr;q=0.8,bs;q=0.7
Cookie: ***
Host: ***
Referer: ***
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
Origin: ***
Content-Length: 4
access-control-allow-origin: *
administration: true
lcid: 2057
access-control-allow-methods: *
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
MS-ASPNETCORE-TOKEN: ***
X-Original-Proto: http
X-Original-For: 127.0.0.1:45856`

This only happens when we set the "UseUnicodeNames" option in the obfuscar.xml config to true

### This is our config
`<?xml version='1.0'?>
<Obfuscator>
  <AssemblySearchPath path="***" />
  <AssemblySearchPath path="***" />
  <Var name="InPath" value=".\" />
  <Var name="OutPath" value=".\Obfuscated" />
  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="false" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  
  <Module file="$(InPath)\***.dll" />
</Obfuscator>`

**Comment by pigiax** [comment]
Same issue. Any workaround or fix?

**Comment by zlatkolakisic** [comment]
@pigiax yes, you have to play around with the config on the projects in question, it was trial and error for us. Not much more help than that.

**Comment by pigiax** [comment]
Ok, for the moment it seems to be fixed with **UseKoreanNames** instead of **UseUnicodeNames**. Of course we need to continue to check if everything continues to work

**Comment by TechnikEmpire** [comment]
@zlatkolakisic It would be super great if you could share ***what*** code you were having an issue with and ***what exactly*** fixed it.

**Comment by zlatkolakisic** [comment]
@TechnikEmpire I cannot share the source as it is not open source, however turning off UseUnicodedNames solved our issue. Could you shed more light on where this could cause issues?

**Comment by TechnikEmpire** [comment]
@zlatkolakisic Of course I understand not being able to share source. But you can still share *metadata* about that source, like what kind of types they were, where those types were being invoked etc.

Also, no, I can't shed more light on it because I'm as lost as you are lol, that's why I made my comment. I ended up working around this issue as far as I can tell by simply excluding the host class/type that the exception was coming from.

**Comment by zlatkolakisic** [comment]
@TechnikEmpire The solution is huge with around 43,000 lines of code so far, I can generate a list of types that are used. Are there any that from your experience proved problematic?

**Comment by TechnikEmpire** [comment]
@zlatkolakisic Just to be clear, I'm not a maintainer or contributor to the project. I'm a user who was just asking if you wouldn't mind sharing your experience with working around this issue because I too faced it. I have no clue what type caused the issue, I just excluded the class that the exception was originating from so it didn't get obfuscated. That's how I solved this problem.

**Comment by pigiax** [comment]
@TechnikEmpire in my case I've started like you, excluding the class causing the issue. But i got same error in another class.
The main cause was that obfuscar renames varibles with a new name composed of two letter. The first letter indicates the class, the second it's a progressive letter. In my case i got a property "Name" obfuscated as "ID". Of course on my class i've already got a property named "Id" and this caused a collision and the issue. To solve I've used this code:

`<?xml version="1.0" encoding="utf-8" ?>
<Obfuscator>
  <Var name="InPath" value="./bin/CI/netcoreapp3.1" />
  <Var name="OutPath" value="$(InPath)/obfuscar_out" />
  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="false" />
  <Var name="UseKoreanNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Var name="ReuseNames" value="false" />
  <Module file="$(InPath)/MyOwn.dll" />
</Obfuscator>`

**Comment by TechnikEmpire** [comment]
@pigiax thanks for sharing.

**Comment by owencyc** [comment]
针对.NET Core项目
<Var name="UseUnicodeNames" value="false" />
  <Var name="UseKoreanNames" value="true" />
需添加这个配置

**Comment by owencyc** [comment]
> @TechnikEmpire in my case I've started like you, excluding the class causing the issue. But i got same error in another class. The main cause was that obfuscar renames varibles with a new name composed of two letter. The first letter indicates the class, the second it's a progressive letter. In my case i got a property "Name" obfuscated as "ID". Of course on my class i've already got a property named "Id" and this caused a collision and the issue. To solve I've used this code:
> 
> ```
> <Obfuscator>
>   <Var name="InPath" value="./bin/CI/netcoreapp3.1" />
>   <Var name="OutPath" value="$(InPath)/obfuscar_out" />
>   <Var name="KeepPublicApi" value="true" />
>   <Var name="HidePrivateApi" value="true" />
>   <Var name="RenameProperties" value="true" />
>   <Var name="RenameEvents" value="true" />
>   <Var name="RenameFields" value="true" />
>   <Var name="UseUnicodeNames" value="false" />
>   <Var name="UseKoreanNames" value="true" />
>   <Var name="HideStrings" value="true" />
>   <Var name="OptimizeMethods" value="true" />
>   <Var name="SuppressIldasm" value="true" />
>   <Var name="ReuseNames" value="false" />
>   <Module file="$(InPath)/MyOwn.dll" />
> </Obfuscator>```
> ```
.NET Core3.1 有效
