### ISSUE TITLE
Exception with Mono.Cecil "Failed to resolve ?."

### ISSUE THREAD

**Issue by mclayton7** [obfuscar/obfuscar#331]
I'm seeing an interesting exception with Obfuscar where during saving the assemblies I get the following exception:
```
Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve ?.'
```
I've tried modifying the libraries and enabling/disabling which ones get obfuscated but it's been difficult to narrow down the issue.

## obfuscar.xml
```xml
<?xml version='1.0'?>
<Obfuscator>
  <AssemblySearchPath path="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.viewfeatures\2.2.0\lib\netstandard2.0" />
  <AssemblySearchPath path="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.abstractions\2.2.0\lib\netstandard2.0" />
  <AssemblySearchPath path="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.core\2.2.0\lib\netstandard2.0" />

  <Var name="InPath" value="." />
  <Var name="OutPath" value=".\Obfuscated" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Var name="XmlMapping" value="true" />

  <Module file="$(InPath)\MyLibrary.dll" />
  <Module file="...other libraries..." />
  <Module file="$(InPath)\MyApplication.dll" />
</Obfuscator>
```

## Console Output
```
  Loading project obfuscar.xml...Processing assembly: MyLibrary, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  Processing assembly: MyApplication, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  Loading assemblies...Extra framework folders: Done.
  Hiding strings...
  Renaming:  fields...Parameters...Properties...Events...Methods...Types...Done.

Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve ?.'
     at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
     at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
     at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
     at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
     at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
     at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
     at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddTypes()
     at Mono.Cecil.MetadataBuilder.BuildTypes()
     at Mono.Cecil.MetadataBuilder.BuildModule()
     at Mono.Cecil.MetadataBuilder.BuildMetadata()
     at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
     at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
     at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
     at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException)
     at Obfuscar.Obfuscator.RunRules()
     at Obfuscar.Program.Main(String[] args)
Saving assemblies...
C:\Program Files\dotnet\sdk\5.0.301\Microsoft.Common.CurrentVersion.targets(5574,5): error MSB3073: The command "C:\Users\clayton\.nuget\packages\obfuscar\2.2.30\build\..\tools\Obfuscar.Console.exe obfuscar.xml" exited with code -532462766. [...]
```

**Comment by lextm** [comment]
It's not clear what's the target framework of the assemblies you were obfuscating.
