### ISSUE TITLE
Obfuscate a linux executable?

### ISSUE THREAD

**Issue by phr00t** [obfuscar/obfuscar#335]
Processing assembly: OpenRPG.Linux, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Unhandled Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Obfuscar.AssemblyInfo.LoadAssembly(String filename)
   at Obfuscar.AssemblyInfo.FromXml(Project project, XElement reader, Variables vars)
   at Obfuscar.Project.FromXmlReadNode(XElement reader, Project project)
   at Obfuscar.Project.FromXml(XDocument reader, String projectFileDirectory)
   at Obfuscar.Obfuscator.LoadFromReader(XDocument reader, String projectFileDirectory)
   at Obfuscar.Obfuscator..ctor(String projfile)
   at Obfuscar.Program.Main(String[] args)

This is when building a C# "Windows application" (e.g. WinExe OutputType) that has a linux-x64 RuntimeIdentifier. The Assembly Name is "OpenRPG.Linux". It isn't either a .exe nor a .dll.... does Obfuscar support Linux executables..?

I did obfuscate the supporting dlls that contain the majority of the game's code, but the OpenRPG.Linux stub to run it no longer succeeds (making me think I need to have the same mapping in OpenRPG.Linux"...

Any help is appreciated!

**Comment by lextm** [comment]
Duplicate to #264

**Comment by lextm** [comment]
Based on your description, `OpenRPG.Linux` is the native bootstrapper generated to merely launch the application with CoreCLR, similar to the `.exe` file generated if you target Windows. Thus, you cannot/should not obfuscate it.
