### ISSUE TITLE
HideString = True Causes Exception In Assembly load which contains only empty string("") with latest 2.2.31 version.

### ISSUE THREAD

**Issue by mantosh4u** [obfuscar/obfuscar#343]
Below sample application can be used to reproduce this issue.

**BasicClass.cs**

```
namespace Basic
{
    public class BasicClass
    {
        private string strMember = "";
        public string StrMember
        {
            get { return strMember; }
            set { strMember = value; }
        }

    }
}

```

**Obfuscated Class Information**
```

// Basic.BasicClass
using <PrivateImplementationDetails>{BC84FD74-F71C-4003-83CD-A378993C5CD7};

public class BasicClass
{
	private string \u200b = 77565F12-006F-4061-A69B-0D6DD352F2A0.\u00a0();

	public string StrMember
	{
		get
		{
			return \u200b;
		}
		set
		{
			\u200b = value;
		}
	}
}




// <PrivateImplementationDetails>{BC84FD74-F71C-4003-83CD-A378993C5CD7}.77565F12-006F-4061-A69B-0D6DD352F2A0
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using <PrivateImplementationDetails>{BC84FD74-F71C-4003-83CD-A378993C5CD7};

[StructLayout(LayoutKind.Auto, CharSet = CharSet.Auto)]
internal class 77565F12-006F-4061-A69B-0D6DD352F2A0
{
	[StructLayout(LayoutKind.Explicit, Pack = 1)]
	private struct 2
	{
	}

	internal static 2 3;

	internal static byte[] 4;

	internal static string[] 5 = new string[1];

	private static string 6(int P_0, int P_1, int P_2)
	{
		string @string = Encoding.UTF8.GetString(4, P_1, P_2);
		5[P_0] = @string;
		return @string;
	}

	public static string \u00a0()
	{
		return 5[0] ?? 6(0, 0, 0);
	}

	static 77565F12-006F-4061-A69B-0D6DD352F2A0()
	{
		byte[] array = new byte[0];
		RuntimeHelpers.InitializeArray(array, (RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/);
		4 = array;
		for (int i = 0; i < 4.Length; i++)
		{
			4[i] = (byte)((uint)(4[i] ^ i) ^ 0xAAu);
		}
	}
}

```

**Sample Application**

```
using System;
using Basic;


namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(">> Obfuscation Main");

            BasicClass x = new BasicClass();


            Console.WriteLine("<< Obfuscation Main");
            Console.WriteLine("Please Enter Something To Complete");
            Console.ReadLine();
        }
    }
}
```

**Output**

>> Obfuscation Main

Unhandled Exception: System.TypeInitializationException: The type initializer for '<PrivateImplementationDetails>{BC84FD74-F71C-4003-83CD-A378993C5CD7}.77565F12-006F-4061-A69B-0D6DD352F2A0' threw an exception. ---> System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.CompilerServices.RuntimeHelpers.InitializeArray(Array array, RuntimeFieldHandle fldHandle)
   at <PrivateImplementationDetails>{BC84FD74-F71C-4003-83CD-A378993C5CD7}.77565F12-006F-4061-A69B-0D6DD352F2A0..cctor()
   --- End of inner exception stack trace ---
   at <PrivateImplementationDetails>{BC84FD74-F71C-4003-83CD-A378993C5CD7}.77565F12-006F-4061-A69B-0D6DD352F2A0. ()
   at ConsoleApp.Program.Main(String[] args) in Program.cs:line 15

Obfuscated assembly should work fine as the above code is valid C# and it compiles(without any warnings) and runs without any issue.  Kindly share the resolution for the same.

**Comment by mantosh4u** [comment]
Any update/comment on this issue.

**Comment by mantosh4u** [comment]
Any update/comment on this issue.

**Comment by lextm** [comment]
You can rewrite it as `string.Empty`.
