### ISSUE TITLE
Methods that take `dynamic` type parameters when called recursively cause errors after obfuscation

### ISSUE THREAD

**Issue by ashutoshbhadoria** [obfuscar/obfuscar#361]
## Problem Summary:
When a private method which takes parameters of `dynamic` type is called recursively, there is an error indicating a missing definition for the method name. On decompiling the assembly, the definition generated for the private method seems incorrect.
However, if the logic of the function is refactored to _iterative_ style instead of _recursive_ style everything works fine.

### Obfuscar.xml
```xml
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="bin\Release\netcoreapp3.1" />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  
  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="ReuseNames" value="false" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Var name="XmlMapping" value="true" />
  
  <Module file="$(InPath)\ConsoleApp1.dll" />
  <Module file="$(InPath)\MyMathClass.dll" />
</Obfuscator>
```

### Recursive Code (Error)
```cs
using System;

namespace MyMathClass
{
    public class MathUtilities
    {
        public string FactorialResult(int number)
        {
            return $"The result of {number}! is {this.CalculateFactorial(number)}";
        }

        // This is the method which causes the issue.
        private int CalculateFactorial(dynamic number)
        {
            if (number == 0) return 1;
            if (number == 1) return 1;
            return number * this.CalculateFactorial(number - 1);
        }
    }
}
```

**Error Output**
```
Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'MyMathClass.MathUtilities' does not contain a definition for 'CalculateFactorial'
   at CallSite.Target(Closure , CallSite , MathUtilities , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at MyMathClass.MathUtilities. (Object number)
   at MyMathClass.MathUtilities.FactorialResult(Int32 number)
   at  . . (String[] )
```
**Decompile Result**
[decompiled_recursive_incorrect.cs.txt](https://github.com/obfuscar/obfuscar/files/8100591/decompiled_recursive_incorrect.cs.txt)

### Iterative Code (Works fine)
```cs
using System;

namespace MyMathClass
{
    public class MathUtilities
    {
        public string FactorialResult(int number)
        {
            return $"The result of {number}! is {this.CalculateFactorial(number)}";
        }

        // Works fine!
        private int CalculateFactorial(dynamic number)
        {
            int result = 1;
            for(int i = number; i > 0; i--)
            {
                result *= i;
            }
            return result;
        }

    }
}

```

**Correct Output**
```
The result of 6! is 720
```

**Decompile Result**
[decompiled_iterative_correct.cs.txt](https://github.com/obfuscar/obfuscar/files/8100589/decompiled_iterative_correct.cs.txt)

**Comment by lextm** [comment]
Things around `dynamic` are heavily name dependent (due to how C# dynamic is implemented), so you need to investigate on your own what should be excluded from obfuscation.
