### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by TheUserOfGithub** [obfuscar/obfuscar#381]
I tried to obfuscate a multiple of libraries and Obfuscar ends with this unhandled exception:
Saving assemblies...Unhandled exception. System.ArgumentException: Member 'System.String <PrivateImplementationDetails>{3E2C000D-8452-4A5D-97AD-A33B5C7FF3A5}.D49B2F18-BFB2-4609-B9D1-53B45A0174B1:: ()' is declared in another module and needs to be imported
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException) in C:\Users\lextudio\source\repos\obfuscar\Obfuscar\Obfuscator.cs:line 296
   at Obfuscar.Obfuscator.RunRules() in C:\Users\lextudio\source\repos\obfuscar\Obfuscar\Obfuscator.cs:line 137
   at Obfuscar.Program.Main(String[] args) in C:\Users\lextudio\source\repos\obfuscar\GlobalTools\Program.cs:line 115

**Comment by lextm** [comment]
Any issue was reported earlier but I didn't have time to finish reviewing/testing it, https://github.com/obfuscar/obfuscar/pull/341

See if it resolves the exception for you.

**Comment by TheUserOfGithub** [comment]
Hello Lex, thank you very much for your response. The case #341 was closed as solved at 13 Sep 2021 and I am using latest nuget package 2.2.33 from the 15th of January 2022. So, it should be solved in this version or not?

**Comment by lextm** [comment]
No. 2.2.33 does not include the changes from #341, and that's why I asked you to try it out.

**Comment by TheUserOfGithub** [comment]
Hello Lex, sorry for delay, I downloaded the obfuscar repository, dependencies and made succesfull build. I added also build result path into path system variables, so I am able to run obfuscar from there. I have still postbuild activity for release build like in the case of trial, where original issue happened. The obfuscar behaviour is different now. It has some problem with paths.This is build output I have now:
20>Note that Rollbar API is enabled by default to collect crashes. If you want to opt out, please run with -s switch
20>Loading project Obfuscar.xml...
20>An error occurred during processing:
20>Unable to find assembly:  .\bin\Release\net6.0-windows\\AppName.dll
20>Failed to resolve assembly: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
Is there some special settings needed if I do not install obfuscar from nuget? I tried also to start obfuscar outside VS from console in project folder (where is the "bin" placed). Then in the build folder and result is stil the same. These two backslash characters in the error message seems suspicious to me. But do not know where they come from. XML file is the same as in the beginning :(

**Comment by lextm** [comment]
Instead of compiling from source code you can now use 2.2.35 release which contains the patch from #341 .

**Comment by TheUserOfGithub** [comment]
Hi Lex, thank you for information.
