### ISSUE TITLE
Unhandled exception. Mono.Cecil.ResolutionException: Failed to resolve System.IO.SearchOption (Easily reproducable)

### ISSUE THREAD

**Issue by AndrewPlakhotnyi** [obfuscar/obfuscar#390]
Obfuscating this code
``` csharp
 public static int SearchDirectory1(SearchOption searchOption = SearchOption.AllDirectories){
      return 1;
  }
```

produces the following error

```
Renaming:  fields...Parameters...Properties...Events...Methods...Types...Done.
Unhandled exception. Mono.Cecil.ResolutionException: Failed to resolve System.IO.SearchOption
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException) in C:\Users\lextudio\source\repos\obfuscar\Obfuscar\Obfuscator.cs:line 296
   at Obfuscar.Obfuscator.RunRules() in C:\Users\lextudio\source\repos\obfuscar\Obfuscar\Obfuscator.cs:line 137
   at Obfuscar.Program.Main(String[] args) in C:\Users\lextudio\source\repos\obfuscar\GlobalTools\Program.cs:line 115
Saving assemblies...
```

This code is obfuscated fine
```csharp
public static int SearchDirectory(SearchOption searchOption){
    var option = System.IO.SearchOption.AllDirectories;
    return (int)option;
}
```

Obfuscar version 2.2.33

**Comment by lextm** [comment]
Thanks for the report, but sounds like a Mono Cecil issue.

**Comment by AndresRohr** [comment]
It's not a Mono Cecil issue, but simply a configuration problem.
For example I had a program that uses 'System.IO.SearchOption' too. Obfuscar looks in all its known assemblies for types. In this case the 'SearchOption' stems from .NET 5 or higher. You need to add each external nunit package in the 'obfuscar.xml' file behind <Module>. For example my .NET 6 based app needed these:

```
	<AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.27\ref\net6.0"/>
	<AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.27\ref\net6.0"/>

```
Now the exception vanished. Hope that helps.
