### ISSUE TITLE
Writing mixed-mode assemblies is not supported

### ISSUE THREAD

**Issue by chenjing1294** [obfuscar/obfuscar#396]
The error occurs when I post in the following way, confusing one of the dll files:
`dotnet publish -c Release --runtime win-x64 -p:PublishReadyToRun=true --self-contained true`

Exception:
```
Saving assemblies...Unhandled exception. System.NotSupportedException: Writing mixed-mode assemblies is not supported
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException) in C:\Users\lextudio\source\repos\obfuscar\Obfuscar\Obfuscator.cs:line 296
   at Obfuscar.Obfuscator.RunRules() in C:\Users\lextudio\source\repos\obfuscar\Obfuscar\Obfuscator.cs:line 137
   at Obfuscar.Program.Main(String[] args) in C:\Users\lextudio\source\repos\obfuscar\GlobalTools\Program.cs:line 115
```

**Comment by chenjing1294** [comment]
> ReadyToRun assemblies are not supported.

Not using ReadyToRun is the same error
