### ISSUE TITLE
exited with code -532462766

### ISSUE THREAD

**Issue by Satindar31** [obfuscar/obfuscar#397]
`>C:\Users\name\source\repos\SimpleSLI\SimpleSLI\SimpleSLI.csproj(39,5): error MSB3073: The command ""C:\Users\name\.nuget\packages\obfuscar\2.2.33\build\..\tools\Obfuscar.Console.exe" obfuscar.xml" exited with code -532462766.`

Build command `"$(Obfuscar)" obfuscar.xml`
obfuscar.xml 
```xml
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="./bin/Release/netcoreapp3.1" />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Module file="$(InPath)\SimpleCLI.exe" />
</Obfuscator>
```

**Comment by lextm** [comment]
As the error message from MSBuild showed you what command failed, you are supposed to run it at command prompt and see what exactly the error is.

**Comment by Satindar31** [comment]
> As the error message from MSBuild showed you what command failed, you are supposed to run it at command prompt and see what exactly the error is.

Uhh I'm not sure what to do exactly, could you give me the command to do so?

**Comment by Satindar31** [comment]
```shell
Note that Rollbar API is enabled by default to collect crashes. If you want to opt out, please run with -s switch
Loading project obfuscar.xml...
Unhandled Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics)
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Obfuscar.AssemblyInfo.LoadAssembly(String filename)
   at Obfuscar.AssemblyInfo.FromXml(Project project, XElement reader, String file, Variables vars)
   at Obfuscar.Project.ReadModule(String file, XElement module, Project project)
   at Obfuscar.Project.ReadModules(XElement reader, Project project)
   at Obfuscar.Project.FromXmlReadNode(XElement reader, Project project)
   at Obfuscar.Project.FromXml(XDocument reader, String projectFileDirectory)
   at Obfuscar.Obfuscator.LoadFromReader(XDocument reader, String projectFileDirectory)
   at Obfuscar.Obfuscator..ctor(String projfile)
   at Obfuscar.Program.Main(String[] args)
```

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq#how-to-troubleshoot-badimageformatexception
