### ISSUE TITLE
Empty resources fail with BadImageFormatException

### ISSUE THREAD

**Issue by PatrickHofman** [obfuscar/obfuscar#452]
When obfuscating assemblies that contain empty embedded resources, obfuscation fails with the error message below:

```
Loading assemblies...Extra framework folders: Done.
Hiding strings...
Renaming:  fields...Parameters...Properties...Events...Methods...Types...

*** stderr ***

Unhandled Exception: System.BadImageFormatException: Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file. ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at System.Resources.ResourceReader._ReadResources()
   at System.Resources.ResourceReader.ReadResources()
   --- End of inner exception stack trace ---
   at System.Resources.ResourceReader.ReadResources()
   at Obfuscar.Obfuscator.GetXamlDocuments(AssemblyDefinition library, Boolean analyzeXaml)
```

Since empty resources are not useful for the intention of this method (`GetXamlDocuments`), I would suggest to ignore empty streams (check after `Stream s = embed.GetResourceStream();`) or simply catch and ignore the `BadImageFormatException`.

**Comment by lextm** [comment]
Similar to #208 and #268 but like you described the actual cause was empty resource, instead of resource for serialization.

I think #324 addressed them all.
