### ISSUE TITLE
Unhandled Exception: System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by lextudio-support** [obfuscar/obfuscar#503]
Hi.

Thank you for Obfuscar 2.0 rc7.

Windows 7 x64 SP1

From within a command prompt, running:
Obfuscar.Console.exe /?

Causes the following output:
Obfuscar is available at http://obfuscar.codeplex.com.
(C) 2007-2014, Ryan Williams and other contributors.

Loading project...
Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share)
   at Obfuscar.Obfuscator..ctor(String projfile)
   at Obfuscar.Program.Main(String[] args)

And produces the following dialog to appear:
[Window Title]
Obfuscar Console Utility

[Main Instruction]
Obfuscar Console Utility has stopped working

[Content]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

[Debug] [Close program]

I expected to see "usage" information for the console application command line parameters/options instead of a crash.

Thank you.

**Original Reported Date**: 2014-05-07T17:56:39.697-07:00
**Planned For Release**: 
**Original CodePlex ID**: 9

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

This is desired, as /? is not yet supported. Will consider it in vNext.

Thanks for the report.

**Original Posted Date**: 2014-05-31T19:12:56.11-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Fixed in 2.0.2 beta.

**Original Posted Date**: 2015-04-17T23:41:05.687-07:00

**Comment by lextudio-support** [comment]
**Original Closed Date**: 2015-04-17T23:41:12.63-07:00
