### ISSUE TITLE
Unhandled Exception: Mono.Cecil.ResolutionException

### ISSUE THREAD

**Issue by lextudio-support** [obfuscar/obfuscar#506]
I get the following error when running obsfuscator:

Saving assemblies...
Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve Eurosoft.
CORE.Native.CoreStrings/StringIDs
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeEnumValue(TypeReference enu
m_type, Object value)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeElement(TypeReference type,
 CustomAttributeArgument argument)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeFixedArgument(TypeReference
 type, CustomAttributeArgument argument)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeConstructorArguments(Custom
Attribute attribute)
   at Mono.Cecil.MetadataBuilder.GetCustomAttributeSignature(CustomAttribute att
ribute)
   at Mono.Cecil.MetadataBuilder.AddCustomAttributes(ICustomAttributeProvider ow
ner)
   at Mono.Cecil.MetadataBuilder.AddProperty(PropertyDefinition property)
   at Mono.Cecil.MetadataBuilder.AddProperties(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypeDefs()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, Metad
ataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stre
am, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parame
ters)
   at Obfuscar.Obfuscator.SaveAssemblies()
   at Obfuscar.Obfuscator.RunRules()
   at Obfuscar.Program.Main(String[] args)

Attached is my project file.

Thanks

**Original Reported Date**: 2015-09-02T05:30:34.31-07:00
**Planned For Release**: 
**Original CodePlex ID**: 29

**Comment by lextudio-support** [comment]
Without accessing to the assemblies, it is impossible to reproduce with such little info. If you like, you can share the assemblies with me via support@lextm.com.

**Original Closed Date**: 2015-09-04T17:54:13.367-07:00
